
services:

  loan-rule-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: aishwaryamehrotra/loan-rule-engine:latest
    container_name: loan-rule-engine
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8080:8080"

    depends_on:
      - kafka

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/loan-rule-engine/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
     - monitoring

  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - loan-rule-engine

  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka

    ports:
      - "9092:9092"

    environment:
      # Host applications -> localhost:9092
      # Docker containers -> kafka:9093
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Single-node development setup
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
  prometheus-data: